export const Activeproducts = [
	{
		id: 0,
		client_company: 'Hyundai Engineering',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			east: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.12.2024',
		client_status: true,
	},
	{
		id: 1,
		client_company: 'GS Engineering & Construction',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '05.09.2024',
		client_status: true,
	},
	{
		id: 2,
		client_company: 'Doosan',
		number_of_buildings: 6,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.11.2024',
		client_status: true,
	},
	{
		id: 3,
		client_company: 'Murad Buildings',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.09.2024',
		client_status: true,
	},
	{
		id: 4,
		client_company: 'GS Holdings',
		number_of_buildings: 5,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.09.2024',
		client_status: true,
	},
	{
		id: 5,
		client_company: 'Advan Construction Co., Ltd',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.10.2024',
		client_status: true,
	},
	{
		id: 0,
		client_company: 'Hyundai Engineering',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			east: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.12.2024',
		client_status: true,
	},
	{
		id: 1,
		client_company: 'GS Engineering & Construction',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '05.09.2024',
		client_status: true,
	},
	{
		id: 2,
		client_company: 'Doosan',
		number_of_buildings: 6,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.11.2024',
		client_status: true,
	},
	{
		id: 3,
		client_company: 'Murad Buildings',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.09.2024',
		client_status: true,
	},
	{
		id: 4,
		client_company: 'GS Holdings',
		number_of_buildings: 5,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.09.2024',
		client_status: true,
	},
	{
		id: 5,
		client_company: 'Advan Construction Co., Ltd',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.10.2024',
		client_status: true,
	},
]

// ========= All Users testing data ======== //
export const TestingUSers = [
	{
		_id: 1,
		user_name: 'Yusuf',
		user_email: 'stranger@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
	{
		_id: 2,
		user_name: 'Muhammad',
		user_email: 'strangerBellimo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 3,
		user_name: 'Abdulloh',
		user_email: 'Bellimo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
	{
		_id: 4,
		user_name: 'Andrew',
		user_email: 'sammi@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 5,
		user_name: 'Jack',
		user_email: 'jpo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 6,
		user_name: 'Ali',
		user_email: 'dsfg@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
	{
		_id: 7,
		user_name: 'Izabella',
		user_email: 'bcvxdsare@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 8,
		user_name: 'Rayhon',
		user_email: 'rha@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 1,
		user_name: 'Yusuf',
		user_email: 'stranger@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 2,
		user_name: 'Muhammad',
		user_email: 'strangerBellimo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
	{
		_id: 3,
		user_name: 'Abdulloh',
		user_email: 'Bellimo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 4,
		user_name: 'Andrew',
		user_email: 'sammi@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 5,
		user_name: 'Jack',
		user_email: 'jpo@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
	{
		_id: 6,
		user_name: 'Ali',
		user_email: 'dsfg@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 7,
		user_name: 'Izabella',
		user_email: 'bcvxdsare@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'USER',
	},
	{
		_id: 8,
		user_name: 'Rayhon',
		user_email: 'rha@gamil.com',
		user_phone: 123456765432,
		user_title: 'WORKER',
		user_type: 'CLIENT',
	},
]
