export const Activeproducts = [
	{
		id: 0,
		client_company: 'Hyundai Engineering',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			east: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.12.2024',
		client_status: true,
	},
	{
		id: 1,
		client_company: 'GS Engineering & Construction',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '05.09.2024',
		client_status: true,
	},
	{
		id: 2,
		client_company: 'Doosan',
		number_of_buildings: 6,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.11.2024',
		client_status: true,
	},
	{
		id: 3,
		client_company: 'Murad Buildings',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.09.2024',
		client_status: true,
	},
	{
		id: 4,
		client_company: 'GS Holdings',
		number_of_buildings: 5,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.09.2024',
		client_status: true,
	},
	{
		id: 5,
		client_company: 'Advan Construction Co., Ltd',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.10.2024',
		client_status: true,
	},
	{
		id: 0,
		client_company: 'Hyundai Engineering',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			east: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.12.2024',
		client_status: true,
	},
	{
		id: 1,
		client_company: 'GS Engineering & Construction',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '05.09.2024',
		client_status: true,
	},
	{
		id: 2,
		client_company: 'Doosan',
		number_of_buildings: 6,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.11.2024',
		client_status: true,
	},
	{
		id: 3,
		client_company: 'Murad Buildings',
		number_of_buildings: 4,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.09.2024',
		client_status: true,
	},
	{
		id: 4,
		client_company: 'GS Holdings',
		number_of_buildings: 5,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '07.09.2024',
		client_status: true,
	},
	{
		id: 5,
		client_company: 'Advan Construction Co., Ltd',
		number_of_buildings: 2,
		buildings_addresses: '경기도 고양시 대덕구 108길 12',
		client_users: {
			user1_boss: '김상민',
			user2_user: '강구빈',
			user3_user: '배윤재',
			user4_user: '강현민',
		},
		using_gateWays: {
			south: [1, 2, 4, 5],
			north: [3, 5, 7],
			west: [],
			easrt: [4, 6, 8, 9],
		},
		permit_date: '15.10.2023',
		expiry_date: '14.10.2024',
		client_status: true,
	},
]
